
//input ports
add mapped point CLK CLK -type PI PI
add mapped point RSTN RSTN -type PI PI
add mapped point PADDR[11] PADDR[11] -type PI PI
add mapped point PADDR[10] PADDR[10] -type PI PI
add mapped point PADDR[9] PADDR[9] -type PI PI
add mapped point PADDR[8] PADDR[8] -type PI PI
add mapped point PADDR[7] PADDR[7] -type PI PI
add mapped point PADDR[6] PADDR[6] -type PI PI
add mapped point PADDR[5] PADDR[5] -type PI PI
add mapped point PADDR[4] PADDR[4] -type PI PI
add mapped point PADDR[3] PADDR[3] -type PI PI
add mapped point PADDR[2] PADDR[2] -type PI PI
add mapped point PADDR[1] PADDR[1] -type PI PI
add mapped point PADDR[0] PADDR[0] -type PI PI
add mapped point PWDATA[31] PWDATA[31] -type PI PI
add mapped point PWDATA[30] PWDATA[30] -type PI PI
add mapped point PWDATA[29] PWDATA[29] -type PI PI
add mapped point PWDATA[28] PWDATA[28] -type PI PI
add mapped point PWDATA[27] PWDATA[27] -type PI PI
add mapped point PWDATA[26] PWDATA[26] -type PI PI
add mapped point PWDATA[25] PWDATA[25] -type PI PI
add mapped point PWDATA[24] PWDATA[24] -type PI PI
add mapped point PWDATA[23] PWDATA[23] -type PI PI
add mapped point PWDATA[22] PWDATA[22] -type PI PI
add mapped point PWDATA[21] PWDATA[21] -type PI PI
add mapped point PWDATA[20] PWDATA[20] -type PI PI
add mapped point PWDATA[19] PWDATA[19] -type PI PI
add mapped point PWDATA[18] PWDATA[18] -type PI PI
add mapped point PWDATA[17] PWDATA[17] -type PI PI
add mapped point PWDATA[16] PWDATA[16] -type PI PI
add mapped point PWDATA[15] PWDATA[15] -type PI PI
add mapped point PWDATA[14] PWDATA[14] -type PI PI
add mapped point PWDATA[13] PWDATA[13] -type PI PI
add mapped point PWDATA[12] PWDATA[12] -type PI PI
add mapped point PWDATA[11] PWDATA[11] -type PI PI
add mapped point PWDATA[10] PWDATA[10] -type PI PI
add mapped point PWDATA[9] PWDATA[9] -type PI PI
add mapped point PWDATA[8] PWDATA[8] -type PI PI
add mapped point PWDATA[7] PWDATA[7] -type PI PI
add mapped point PWDATA[6] PWDATA[6] -type PI PI
add mapped point PWDATA[5] PWDATA[5] -type PI PI
add mapped point PWDATA[4] PWDATA[4] -type PI PI
add mapped point PWDATA[3] PWDATA[3] -type PI PI
add mapped point PWDATA[2] PWDATA[2] -type PI PI
add mapped point PWDATA[1] PWDATA[1] -type PI PI
add mapped point PWDATA[0] PWDATA[0] -type PI PI
add mapped point PWRITE PWRITE -type PI PI
add mapped point PSEL PSEL -type PI PI
add mapped point PENABLE PENABLE -type PI PI
add mapped point uart_sin uart_sin -type PI PI
add mapped point uart_cts_n uart_cts_n -type PI PI
add mapped point uart_dsr_n uart_dsr_n -type PI PI
add mapped point uart_ri_n uart_ri_n -type PI PI
add mapped point uart_dcd_n uart_dcd_n -type PI PI
add mapped point dma_tx_ack dma_tx_ack -type PI PI
add mapped point dma_rx_ack dma_rx_ack -type PI PI

//output ports
add mapped point PRDATA[31] PRDATA[31] -type PO PO
add mapped point PRDATA[30] PRDATA[30] -type PO PO
add mapped point PRDATA[29] PRDATA[29] -type PO PO
add mapped point PRDATA[28] PRDATA[28] -type PO PO
add mapped point PRDATA[27] PRDATA[27] -type PO PO
add mapped point PRDATA[26] PRDATA[26] -type PO PO
add mapped point PRDATA[25] PRDATA[25] -type PO PO
add mapped point PRDATA[24] PRDATA[24] -type PO PO
add mapped point PRDATA[23] PRDATA[23] -type PO PO
add mapped point PRDATA[22] PRDATA[22] -type PO PO
add mapped point PRDATA[21] PRDATA[21] -type PO PO
add mapped point PRDATA[20] PRDATA[20] -type PO PO
add mapped point PRDATA[19] PRDATA[19] -type PO PO
add mapped point PRDATA[18] PRDATA[18] -type PO PO
add mapped point PRDATA[17] PRDATA[17] -type PO PO
add mapped point PRDATA[16] PRDATA[16] -type PO PO
add mapped point PRDATA[15] PRDATA[15] -type PO PO
add mapped point PRDATA[14] PRDATA[14] -type PO PO
add mapped point PRDATA[13] PRDATA[13] -type PO PO
add mapped point PRDATA[12] PRDATA[12] -type PO PO
add mapped point PRDATA[11] PRDATA[11] -type PO PO
add mapped point PRDATA[10] PRDATA[10] -type PO PO
add mapped point PRDATA[9] PRDATA[9] -type PO PO
add mapped point PRDATA[8] PRDATA[8] -type PO PO
add mapped point PRDATA[7] PRDATA[7] -type PO PO
add mapped point PRDATA[6] PRDATA[6] -type PO PO
add mapped point PRDATA[5] PRDATA[5] -type PO PO
add mapped point PRDATA[4] PRDATA[4] -type PO PO
add mapped point PRDATA[3] PRDATA[3] -type PO PO
add mapped point PRDATA[2] PRDATA[2] -type PO PO
add mapped point PRDATA[1] PRDATA[1] -type PO PO
add mapped point PRDATA[0] PRDATA[0] -type PO PO
add mapped point PREADY PREADY -type PO PO
add mapped point PSLVERR PSLVERR -type PO PO
add mapped point uart_sout uart_sout -type PO PO
add mapped point uart_rts_n uart_rts_n -type PO PO
add mapped point uart_dtr_n uart_dtr_n -type PO PO
add mapped point uart_out1_n uart_out1_n -type PO PO
add mapped point uart_out2_n uart_out2_n -type PO PO
add mapped point uart_int uart_int -type PO PO
add mapped point tx_int tx_int -type PO PO
add mapped point rx_int rx_int -type PO PO
add mapped point rxovr_int rxovr_int -type PO PO
add mapped point txovr_int txovr_int -type PO PO
add mapped point dma_tx_req dma_tx_req -type PO PO
add mapped point dma_tx_single dma_tx_single -type PO PO
add mapped point dma_rx_req dma_rx_req -type PO PO
add mapped point dma_rx_single dma_rx_single -type PO PO

//inout ports




//Sequential Pins
add mapped point u_dma/tx_req_r/q u_dma/tx_req_r_reg/Q -type DFF DFF
add mapped point u_dma/rx_single_r/q u_dma/rx_single_r_reg/Q -type DFF DFF
add mapped point u_dma/tx_single_r/q u_dma/tx_single_r_reg/Q -type DFF DFF
add mapped point u_dma/rx_req_r/q u_dma/rx_req_r_reg/Q -type DFF DFF
add mapped point u_intf_block/cts_prev/q u_intf_block/cts_prev_reg/Q -type DFF DFF
add mapped point u_intf_block/dcd_prev/q u_intf_block/dcd_prev_reg/Q -type DFF DFF
add mapped point u_intf_block/dsr_prev/q u_intf_block/dsr_prev_reg/Q -type DFF DFF
add mapped point u_intf_block/ri_prev/q u_intf_block/ri_prev_reg/Q -type DFF DFF
add mapped point u_intf_block/ri_ff2/q u_intf_block/ri_ff2_reg/Q -type DFF DFF
add mapped point u_intf_block/dcd_ff2/q u_intf_block/dcd_ff2_reg/Q -type DFF DFF
add mapped point u_intf_block/dsr_ff2/q u_intf_block/dsr_ff2_reg/Q -type DFF DFF
add mapped point u_intf_block/cts_ff2/q u_intf_block/cts_ff2_reg/Q -type DFF DFF
add mapped point u_intf_block/cts_ff1/q u_intf_block/cts_ff1_reg/Q -type DFF DFF
add mapped point u_intf_block/ri_ff1/q u_intf_block/ri_ff1_reg/Q -type DFF DFF
add mapped point u_intf_block/dcd_ff1/q u_intf_block/dcd_ff1_reg/Q -type DFF DFF
add mapped point u_intf_block/dsr_ff1/q u_intf_block/dsr_ff1_reg/Q -type DFF DFF
add mapped point u_intf_block/dcts_r/q u_intf_block/dcts_r_reg/Q -type DFF DFF
add mapped point u_intf_block/ddcd_r/q u_intf_block/ddcd_r_reg/Q -type DFF DFF
add mapped point u_intf_block/ddsr_r/q u_intf_block/ddsr_r_reg/Q -type DFF DFF
add mapped point u_intf_block/teri_r/q u_intf_block/teri_r_reg/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][0]/q u_uart_core/u_rx_fifo/buffer_regx0xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][1]/q u_uart_core/u_rx_fifo/buffer_regx0xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][2]/q u_uart_core/u_rx_fifo/buffer_regx0xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][3]/q u_uart_core/u_rx_fifo/buffer_regx0xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][4]/q u_uart_core/u_rx_fifo/buffer_regx0xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][5]/q u_uart_core/u_rx_fifo/buffer_regx0xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][6]/q u_uart_core/u_rx_fifo/buffer_regx0xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[0][7]/q u_uart_core/u_rx_fifo/buffer_regx0xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][0]/q u_uart_core/u_rx_fifo/buffer_regx1xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][1]/q u_uart_core/u_rx_fifo/buffer_regx1xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][2]/q u_uart_core/u_rx_fifo/buffer_regx1xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][3]/q u_uart_core/u_rx_fifo/buffer_regx1xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][4]/q u_uart_core/u_rx_fifo/buffer_regx1xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][5]/q u_uart_core/u_rx_fifo/buffer_regx1xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][6]/q u_uart_core/u_rx_fifo/buffer_regx1xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[1][7]/q u_uart_core/u_rx_fifo/buffer_regx1xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][0]/q u_uart_core/u_rx_fifo/buffer_regx2xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][1]/q u_uart_core/u_rx_fifo/buffer_regx2xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][2]/q u_uart_core/u_rx_fifo/buffer_regx2xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][3]/q u_uart_core/u_rx_fifo/buffer_regx2xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][4]/q u_uart_core/u_rx_fifo/buffer_regx2xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][5]/q u_uart_core/u_rx_fifo/buffer_regx2xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][6]/q u_uart_core/u_rx_fifo/buffer_regx2xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[2][7]/q u_uart_core/u_rx_fifo/buffer_regx2xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][0]/q u_uart_core/u_rx_fifo/buffer_regx3xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][1]/q u_uart_core/u_rx_fifo/buffer_regx3xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][2]/q u_uart_core/u_rx_fifo/buffer_regx3xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][3]/q u_uart_core/u_rx_fifo/buffer_regx3xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][4]/q u_uart_core/u_rx_fifo/buffer_regx3xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][5]/q u_uart_core/u_rx_fifo/buffer_regx3xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][6]/q u_uart_core/u_rx_fifo/buffer_regx3xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[3][7]/q u_uart_core/u_rx_fifo/buffer_regx3xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][0]/q u_uart_core/u_rx_fifo/buffer_regx4xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][1]/q u_uart_core/u_rx_fifo/buffer_regx4xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][2]/q u_uart_core/u_rx_fifo/buffer_regx4xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][3]/q u_uart_core/u_rx_fifo/buffer_regx4xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][4]/q u_uart_core/u_rx_fifo/buffer_regx4xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][5]/q u_uart_core/u_rx_fifo/buffer_regx4xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][6]/q u_uart_core/u_rx_fifo/buffer_regx4xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[4][7]/q u_uart_core/u_rx_fifo/buffer_regx4xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][0]/q u_uart_core/u_rx_fifo/buffer_regx5xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][1]/q u_uart_core/u_rx_fifo/buffer_regx5xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][2]/q u_uart_core/u_rx_fifo/buffer_regx5xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][3]/q u_uart_core/u_rx_fifo/buffer_regx5xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][4]/q u_uart_core/u_rx_fifo/buffer_regx5xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][5]/q u_uart_core/u_rx_fifo/buffer_regx5xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][6]/q u_uart_core/u_rx_fifo/buffer_regx5xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[5][7]/q u_uart_core/u_rx_fifo/buffer_regx5xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][0]/q u_uart_core/u_rx_fifo/buffer_regx6xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][1]/q u_uart_core/u_rx_fifo/buffer_regx6xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][2]/q u_uart_core/u_rx_fifo/buffer_regx6xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][3]/q u_uart_core/u_rx_fifo/buffer_regx6xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][4]/q u_uart_core/u_rx_fifo/buffer_regx6xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][5]/q u_uart_core/u_rx_fifo/buffer_regx6xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][6]/q u_uart_core/u_rx_fifo/buffer_regx6xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[6][7]/q u_uart_core/u_rx_fifo/buffer_regx6xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][0]/q u_uart_core/u_rx_fifo/buffer_regx7xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][1]/q u_uart_core/u_rx_fifo/buffer_regx7xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][2]/q u_uart_core/u_rx_fifo/buffer_regx7xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][3]/q u_uart_core/u_rx_fifo/buffer_regx7xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][4]/q u_uart_core/u_rx_fifo/buffer_regx7xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][5]/q u_uart_core/u_rx_fifo/buffer_regx7xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][6]/q u_uart_core/u_rx_fifo/buffer_regx7xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[7][7]/q u_uart_core/u_rx_fifo/buffer_regx7xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][0]/q u_uart_core/u_rx_fifo/buffer_regx8xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][1]/q u_uart_core/u_rx_fifo/buffer_regx8xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][2]/q u_uart_core/u_rx_fifo/buffer_regx8xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][3]/q u_uart_core/u_rx_fifo/buffer_regx8xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][4]/q u_uart_core/u_rx_fifo/buffer_regx8xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][5]/q u_uart_core/u_rx_fifo/buffer_regx8xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][6]/q u_uart_core/u_rx_fifo/buffer_regx8xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[8][7]/q u_uart_core/u_rx_fifo/buffer_regx8xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][0]/q u_uart_core/u_rx_fifo/buffer_regx9xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][1]/q u_uart_core/u_rx_fifo/buffer_regx9xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][2]/q u_uart_core/u_rx_fifo/buffer_regx9xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][3]/q u_uart_core/u_rx_fifo/buffer_regx9xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][4]/q u_uart_core/u_rx_fifo/buffer_regx9xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][5]/q u_uart_core/u_rx_fifo/buffer_regx9xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][6]/q u_uart_core/u_rx_fifo/buffer_regx9xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[9][7]/q u_uart_core/u_rx_fifo/buffer_regx9xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][0]/q u_uart_core/u_rx_fifo/buffer_regx10xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][1]/q u_uart_core/u_rx_fifo/buffer_regx10xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][2]/q u_uart_core/u_rx_fifo/buffer_regx10xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][3]/q u_uart_core/u_rx_fifo/buffer_regx10xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][4]/q u_uart_core/u_rx_fifo/buffer_regx10xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][5]/q u_uart_core/u_rx_fifo/buffer_regx10xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][6]/q u_uart_core/u_rx_fifo/buffer_regx10xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[10][7]/q u_uart_core/u_rx_fifo/buffer_regx10xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][0]/q u_uart_core/u_rx_fifo/buffer_regx11xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][1]/q u_uart_core/u_rx_fifo/buffer_regx11xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][2]/q u_uart_core/u_rx_fifo/buffer_regx11xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][3]/q u_uart_core/u_rx_fifo/buffer_regx11xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][4]/q u_uart_core/u_rx_fifo/buffer_regx11xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][5]/q u_uart_core/u_rx_fifo/buffer_regx11xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][6]/q u_uart_core/u_rx_fifo/buffer_regx11xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[11][7]/q u_uart_core/u_rx_fifo/buffer_regx11xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][0]/q u_uart_core/u_rx_fifo/buffer_regx12xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][1]/q u_uart_core/u_rx_fifo/buffer_regx12xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][2]/q u_uart_core/u_rx_fifo/buffer_regx12xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][3]/q u_uart_core/u_rx_fifo/buffer_regx12xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][4]/q u_uart_core/u_rx_fifo/buffer_regx12xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][5]/q u_uart_core/u_rx_fifo/buffer_regx12xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][6]/q u_uart_core/u_rx_fifo/buffer_regx12xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[12][7]/q u_uart_core/u_rx_fifo/buffer_regx12xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][0]/q u_uart_core/u_rx_fifo/buffer_regx13xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][1]/q u_uart_core/u_rx_fifo/buffer_regx13xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][2]/q u_uart_core/u_rx_fifo/buffer_regx13xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][3]/q u_uart_core/u_rx_fifo/buffer_regx13xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][4]/q u_uart_core/u_rx_fifo/buffer_regx13xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][5]/q u_uart_core/u_rx_fifo/buffer_regx13xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][6]/q u_uart_core/u_rx_fifo/buffer_regx13xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[13][7]/q u_uart_core/u_rx_fifo/buffer_regx13xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][0]/q u_uart_core/u_rx_fifo/buffer_regx14xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][1]/q u_uart_core/u_rx_fifo/buffer_regx14xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][2]/q u_uart_core/u_rx_fifo/buffer_regx14xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][3]/q u_uart_core/u_rx_fifo/buffer_regx14xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][4]/q u_uart_core/u_rx_fifo/buffer_regx14xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][5]/q u_uart_core/u_rx_fifo/buffer_regx14xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][6]/q u_uart_core/u_rx_fifo/buffer_regx14xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[14][7]/q u_uart_core/u_rx_fifo/buffer_regx14xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][0]/q u_uart_core/u_rx_fifo/buffer_regx15xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][1]/q u_uart_core/u_rx_fifo/buffer_regx15xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][2]/q u_uart_core/u_rx_fifo/buffer_regx15xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][3]/q u_uart_core/u_rx_fifo/buffer_regx15xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][4]/q u_uart_core/u_rx_fifo/buffer_regx15xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][5]/q u_uart_core/u_rx_fifo/buffer_regx15xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][6]/q u_uart_core/u_rx_fifo/buffer_regx15xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/buffer[15][7]/q u_uart_core/u_rx_fifo/buffer_regx15xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/elements[4]/q u_uart_core/u_rx_fifo/elements_regx4x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/elements[3]/q u_uart_core/u_rx_fifo/elements_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/elements[2]/q u_uart_core/u_rx_fifo/elements_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_in[3]/q u_uart_core/u_rx_fifo/pointer_in_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/elements[1]/q u_uart_core/u_rx_fifo/elements_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_out[3]/q u_uart_core/u_rx_fifo/pointer_out_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_in[2]/q u_uart_core/u_rx_fifo/pointer_in_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_out[2]/q u_uart_core/u_rx_fifo/pointer_out_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_in[1]/q u_uart_core/u_rx_fifo/pointer_in_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_out[1]/q u_uart_core/u_rx_fifo/pointer_out_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_in[0]/q u_uart_core/u_rx_fifo/pointer_in_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/pointer_out[0]/q u_uart_core/u_rx_fifo/pointer_out_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_rx_fifo/elements[0]/q u_uart_core/u_rx_fifo/elements_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][0]/q u_uart_core/u_tx_fifo/buffer_regx0xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][1]/q u_uart_core/u_tx_fifo/buffer_regx0xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][2]/q u_uart_core/u_tx_fifo/buffer_regx0xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][3]/q u_uart_core/u_tx_fifo/buffer_regx0xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][4]/q u_uart_core/u_tx_fifo/buffer_regx0xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][5]/q u_uart_core/u_tx_fifo/buffer_regx0xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][6]/q u_uart_core/u_tx_fifo/buffer_regx0xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[0][7]/q u_uart_core/u_tx_fifo/buffer_regx0xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][0]/q u_uart_core/u_tx_fifo/buffer_regx1xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][1]/q u_uart_core/u_tx_fifo/buffer_regx1xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][2]/q u_uart_core/u_tx_fifo/buffer_regx1xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][3]/q u_uart_core/u_tx_fifo/buffer_regx1xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][4]/q u_uart_core/u_tx_fifo/buffer_regx1xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][5]/q u_uart_core/u_tx_fifo/buffer_regx1xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][6]/q u_uart_core/u_tx_fifo/buffer_regx1xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[1][7]/q u_uart_core/u_tx_fifo/buffer_regx1xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][0]/q u_uart_core/u_tx_fifo/buffer_regx2xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][1]/q u_uart_core/u_tx_fifo/buffer_regx2xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][2]/q u_uart_core/u_tx_fifo/buffer_regx2xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][3]/q u_uart_core/u_tx_fifo/buffer_regx2xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][4]/q u_uart_core/u_tx_fifo/buffer_regx2xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][5]/q u_uart_core/u_tx_fifo/buffer_regx2xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][6]/q u_uart_core/u_tx_fifo/buffer_regx2xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[2][7]/q u_uart_core/u_tx_fifo/buffer_regx2xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][0]/q u_uart_core/u_tx_fifo/buffer_regx3xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][1]/q u_uart_core/u_tx_fifo/buffer_regx3xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][2]/q u_uart_core/u_tx_fifo/buffer_regx3xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][3]/q u_uart_core/u_tx_fifo/buffer_regx3xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][4]/q u_uart_core/u_tx_fifo/buffer_regx3xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][5]/q u_uart_core/u_tx_fifo/buffer_regx3xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][6]/q u_uart_core/u_tx_fifo/buffer_regx3xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[3][7]/q u_uart_core/u_tx_fifo/buffer_regx3xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][0]/q u_uart_core/u_tx_fifo/buffer_regx4xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][1]/q u_uart_core/u_tx_fifo/buffer_regx4xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][2]/q u_uart_core/u_tx_fifo/buffer_regx4xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][3]/q u_uart_core/u_tx_fifo/buffer_regx4xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][4]/q u_uart_core/u_tx_fifo/buffer_regx4xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][5]/q u_uart_core/u_tx_fifo/buffer_regx4xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][6]/q u_uart_core/u_tx_fifo/buffer_regx4xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[4][7]/q u_uart_core/u_tx_fifo/buffer_regx4xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][0]/q u_uart_core/u_tx_fifo/buffer_regx5xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][1]/q u_uart_core/u_tx_fifo/buffer_regx5xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][2]/q u_uart_core/u_tx_fifo/buffer_regx5xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][3]/q u_uart_core/u_tx_fifo/buffer_regx5xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][4]/q u_uart_core/u_tx_fifo/buffer_regx5xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][5]/q u_uart_core/u_tx_fifo/buffer_regx5xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][6]/q u_uart_core/u_tx_fifo/buffer_regx5xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[5][7]/q u_uart_core/u_tx_fifo/buffer_regx5xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][0]/q u_uart_core/u_tx_fifo/buffer_regx6xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][1]/q u_uart_core/u_tx_fifo/buffer_regx6xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][2]/q u_uart_core/u_tx_fifo/buffer_regx6xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][3]/q u_uart_core/u_tx_fifo/buffer_regx6xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][4]/q u_uart_core/u_tx_fifo/buffer_regx6xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][5]/q u_uart_core/u_tx_fifo/buffer_regx6xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][6]/q u_uart_core/u_tx_fifo/buffer_regx6xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[6][7]/q u_uart_core/u_tx_fifo/buffer_regx6xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][0]/q u_uart_core/u_tx_fifo/buffer_regx7xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][1]/q u_uart_core/u_tx_fifo/buffer_regx7xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][2]/q u_uart_core/u_tx_fifo/buffer_regx7xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][3]/q u_uart_core/u_tx_fifo/buffer_regx7xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][4]/q u_uart_core/u_tx_fifo/buffer_regx7xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][5]/q u_uart_core/u_tx_fifo/buffer_regx7xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][6]/q u_uart_core/u_tx_fifo/buffer_regx7xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[7][7]/q u_uart_core/u_tx_fifo/buffer_regx7xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][0]/q u_uart_core/u_tx_fifo/buffer_regx8xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][1]/q u_uart_core/u_tx_fifo/buffer_regx8xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][2]/q u_uart_core/u_tx_fifo/buffer_regx8xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][3]/q u_uart_core/u_tx_fifo/buffer_regx8xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][4]/q u_uart_core/u_tx_fifo/buffer_regx8xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][5]/q u_uart_core/u_tx_fifo/buffer_regx8xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][6]/q u_uart_core/u_tx_fifo/buffer_regx8xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[8][7]/q u_uart_core/u_tx_fifo/buffer_regx8xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][0]/q u_uart_core/u_tx_fifo/buffer_regx9xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][1]/q u_uart_core/u_tx_fifo/buffer_regx9xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][2]/q u_uart_core/u_tx_fifo/buffer_regx9xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][3]/q u_uart_core/u_tx_fifo/buffer_regx9xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][4]/q u_uart_core/u_tx_fifo/buffer_regx9xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][5]/q u_uart_core/u_tx_fifo/buffer_regx9xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][6]/q u_uart_core/u_tx_fifo/buffer_regx9xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[9][7]/q u_uart_core/u_tx_fifo/buffer_regx9xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][0]/q u_uart_core/u_tx_fifo/buffer_regx10xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][1]/q u_uart_core/u_tx_fifo/buffer_regx10xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][2]/q u_uart_core/u_tx_fifo/buffer_regx10xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][3]/q u_uart_core/u_tx_fifo/buffer_regx10xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][4]/q u_uart_core/u_tx_fifo/buffer_regx10xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][5]/q u_uart_core/u_tx_fifo/buffer_regx10xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][6]/q u_uart_core/u_tx_fifo/buffer_regx10xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[10][7]/q u_uart_core/u_tx_fifo/buffer_regx10xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][0]/q u_uart_core/u_tx_fifo/buffer_regx11xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][1]/q u_uart_core/u_tx_fifo/buffer_regx11xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][2]/q u_uart_core/u_tx_fifo/buffer_regx11xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][3]/q u_uart_core/u_tx_fifo/buffer_regx11xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][4]/q u_uart_core/u_tx_fifo/buffer_regx11xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][5]/q u_uart_core/u_tx_fifo/buffer_regx11xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][6]/q u_uart_core/u_tx_fifo/buffer_regx11xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[11][7]/q u_uart_core/u_tx_fifo/buffer_regx11xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][0]/q u_uart_core/u_tx_fifo/buffer_regx12xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][1]/q u_uart_core/u_tx_fifo/buffer_regx12xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][2]/q u_uart_core/u_tx_fifo/buffer_regx12xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][3]/q u_uart_core/u_tx_fifo/buffer_regx12xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][4]/q u_uart_core/u_tx_fifo/buffer_regx12xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][5]/q u_uart_core/u_tx_fifo/buffer_regx12xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][6]/q u_uart_core/u_tx_fifo/buffer_regx12xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[12][7]/q u_uart_core/u_tx_fifo/buffer_regx12xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][0]/q u_uart_core/u_tx_fifo/buffer_regx13xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][1]/q u_uart_core/u_tx_fifo/buffer_regx13xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][2]/q u_uart_core/u_tx_fifo/buffer_regx13xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][3]/q u_uart_core/u_tx_fifo/buffer_regx13xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][4]/q u_uart_core/u_tx_fifo/buffer_regx13xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][5]/q u_uart_core/u_tx_fifo/buffer_regx13xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][6]/q u_uart_core/u_tx_fifo/buffer_regx13xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[13][7]/q u_uart_core/u_tx_fifo/buffer_regx13xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][0]/q u_uart_core/u_tx_fifo/buffer_regx14xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][1]/q u_uart_core/u_tx_fifo/buffer_regx14xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][2]/q u_uart_core/u_tx_fifo/buffer_regx14xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][3]/q u_uart_core/u_tx_fifo/buffer_regx14xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][4]/q u_uart_core/u_tx_fifo/buffer_regx14xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][5]/q u_uart_core/u_tx_fifo/buffer_regx14xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][6]/q u_uart_core/u_tx_fifo/buffer_regx14xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[14][7]/q u_uart_core/u_tx_fifo/buffer_regx14xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][0]/q u_uart_core/u_tx_fifo/buffer_regx15xx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][1]/q u_uart_core/u_tx_fifo/buffer_regx15xx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][2]/q u_uart_core/u_tx_fifo/buffer_regx15xx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][3]/q u_uart_core/u_tx_fifo/buffer_regx15xx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][4]/q u_uart_core/u_tx_fifo/buffer_regx15xx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][5]/q u_uart_core/u_tx_fifo/buffer_regx15xx5x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][6]/q u_uart_core/u_tx_fifo/buffer_regx15xx6x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/buffer[15][7]/q u_uart_core/u_tx_fifo/buffer_regx15xx7x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/elements[4]/q u_uart_core/u_tx_fifo/elements_regx4x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/elements[3]/q u_uart_core/u_tx_fifo/elements_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/elements[2]/q u_uart_core/u_tx_fifo/elements_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/elements[1]/q u_uart_core/u_tx_fifo/elements_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_in[2]/q u_uart_core/u_tx_fifo/pointer_in_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_in[3]/q u_uart_core/u_tx_fifo/pointer_in_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_out[3]/q u_uart_core/u_tx_fifo/pointer_out_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_out[2]/q u_uart_core/u_tx_fifo/pointer_out_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_in[1]/q u_uart_core/u_tx_fifo/pointer_in_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_out[1]/q u_uart_core/u_tx_fifo/pointer_out_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_in[0]/q u_uart_core/u_tx_fifo/pointer_in_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/pointer_out[0]/q u_uart_core/u_tx_fifo/pointer_out_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_tx_fifo/elements[0]/q u_uart_core/u_tx_fifo/elements_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_rx_sync[0]/q u_uart_core/u_uart_rx/reg_rx_sync_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_rx_sync[1]/q u_uart_core/u_uart_rx/reg_rx_sync_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/CS[0]/q u_uart_core/u_uart_rx/CS_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/CS[1]/q u_uart_core/u_uart_rx/CS_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/CS[2]/q u_uart_core/u_uart_rx/CS_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[0]/q u_uart_core/u_uart_rx/baud_cnt_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[1]/q u_uart_core/u_uart_rx/baud_cnt_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[2]/q u_uart_core/u_uart_rx/baud_cnt_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[3]/q u_uart_core/u_uart_rx/baud_cnt_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[4]/q u_uart_core/u_uart_rx/baud_cnt_regx4x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[5]/q u_uart_core/u_uart_rx/baud_cnt_regx5x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[6]/q u_uart_core/u_uart_rx/baud_cnt_regx6x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[7]/q u_uart_core/u_uart_rx/baud_cnt_regx7x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[8]/q u_uart_core/u_uart_rx/baud_cnt_regx8x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[9]/q u_uart_core/u_uart_rx/baud_cnt_regx9x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[10]/q u_uart_core/u_uart_rx/baud_cnt_regx10x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[11]/q u_uart_core/u_uart_rx/baud_cnt_regx11x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[12]/q u_uart_core/u_uart_rx/baud_cnt_regx12x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[13]/q u_uart_core/u_uart_rx/baud_cnt_regx13x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[14]/q u_uart_core/u_uart_rx/baud_cnt_regx14x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/baud_cnt[15]/q u_uart_core/u_uart_rx/baud_cnt_regx15x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/err_o/q u_uart_core/u_uart_rx/err_o_reg/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/parity_bit/q u_uart_core/u_uart_rx/parity_bit_reg/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_bit_count[0]/q u_uart_core/u_uart_rx/reg_bit_count_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_bit_count[1]/q u_uart_core/u_uart_rx/reg_bit_count_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_bit_count[2]/q u_uart_core/u_uart_rx/reg_bit_count_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[6]/q u_uart_core/u_uart_rx/reg_data_regx6x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[4]/q u_uart_core/u_uart_rx/reg_data_regx4x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[5]/q u_uart_core/u_uart_rx/reg_data_regx5x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/bit_done/q u_uart_core/u_uart_rx/bit_done_reg/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[7]/q u_uart_core/u_uart_rx/reg_data_regx7x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[1]/q u_uart_core/u_uart_rx/reg_data_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[2]/q u_uart_core/u_uart_rx/reg_data_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_rx_sync[2]/q u_uart_core/u_uart_rx/reg_rx_sync_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[0]/q u_uart_core/u_uart_rx/reg_data_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_rx/reg_data[3]/q u_uart_core/u_uart_rx/reg_data_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/bit_done/q u_uart_core/u_uart_tx/bit_done_reg/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[0]/q u_uart_core/u_uart_tx/reg_data_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[1]/q u_uart_core/u_uart_tx/reg_data_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[2]/q u_uart_core/u_uart_tx/reg_data_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[3]/q u_uart_core/u_uart_tx/reg_data_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[4]/q u_uart_core/u_uart_tx/reg_data_regx4x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[5]/q u_uart_core/u_uart_tx/reg_data_regx5x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[6]/q u_uart_core/u_uart_tx/reg_data_regx6x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_data[7]/q u_uart_core/u_uart_tx/reg_data_regx7x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/CS[0]/q u_uart_core/u_uart_tx/CS_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/CS[1]/q u_uart_core/u_uart_tx/CS_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/CS[2]/q u_uart_core/u_uart_tx/CS_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[0]/q u_uart_core/u_uart_tx/baud_cnt_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[1]/q u_uart_core/u_uart_tx/baud_cnt_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[2]/q u_uart_core/u_uart_tx/baud_cnt_regx2x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[3]/q u_uart_core/u_uart_tx/baud_cnt_regx3x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[4]/q u_uart_core/u_uart_tx/baud_cnt_regx4x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[5]/q u_uart_core/u_uart_tx/baud_cnt_regx5x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[6]/q u_uart_core/u_uart_tx/baud_cnt_regx6x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[7]/q u_uart_core/u_uart_tx/baud_cnt_regx7x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[8]/q u_uart_core/u_uart_tx/baud_cnt_regx8x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[9]/q u_uart_core/u_uart_tx/baud_cnt_regx9x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[10]/q u_uart_core/u_uart_tx/baud_cnt_regx10x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[11]/q u_uart_core/u_uart_tx/baud_cnt_regx11x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[12]/q u_uart_core/u_uart_tx/baud_cnt_regx12x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[13]/q u_uart_core/u_uart_tx/baud_cnt_regx13x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[14]/q u_uart_core/u_uart_tx/baud_cnt_regx14x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/baud_cnt[15]/q u_uart_core/u_uart_tx/baud_cnt_regx15x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/parity_bit/q u_uart_core/u_uart_tx/parity_bit_reg/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_bit_count[0]/q u_uart_core/u_uart_tx/reg_bit_count_regx0x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_bit_count[1]/q u_uart_core/u_uart_tx/reg_bit_count_regx1x/Q -type DFF DFF
add mapped point u_uart_core/u_uart_tx/reg_bit_count[2]/q u_uart_core/u_uart_tx/reg_bit_count_regx2x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[7]/q u_uart_core/LCR_q_regx7x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[4]/q u_uart_core/IER_q_regx4x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[5]/q u_uart_core/IER_q_regx5x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[6]/q u_uart_core/IER_q_regx6x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[7]/q u_uart_core/IER_q_regx7x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[4]/q u_uart_core/LCR_q_regx4x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[5]/q u_uart_core/LCR_q_regx5x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[0]/q u_uart_core/SCR_q_regx0x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[1]/q u_uart_core/SCR_q_regx1x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[2]/q u_uart_core/SCR_q_regx2x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[3]/q u_uart_core/SCR_q_regx3x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[4]/q u_uart_core/SCR_q_regx4x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[5]/q u_uart_core/SCR_q_regx5x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[6]/q u_uart_core/SCR_q_regx6x/Q -type DFF DFF
add mapped point u_uart_core/SCR_q[7]/q u_uart_core/SCR_q_regx7x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[15]/q u_uart_core/rx_timeout_cnt_regx15x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[13]/q u_uart_core/rx_timeout_cnt_regx13x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[14]/q u_uart_core/rx_timeout_cnt_regx14x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[11]/q u_uart_core/rx_timeout_cnt_regx11x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[12]/q u_uart_core/rx_timeout_cnt_regx12x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[10]/q u_uart_core/rx_timeout_cnt_regx10x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[9]/q u_uart_core/rx_timeout_cnt_regx9x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[8]/q u_uart_core/rx_timeout_cnt_regx8x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[7]/q u_uart_core/rx_timeout_cnt_regx7x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[6]/q u_uart_core/rx_timeout_cnt_regx6x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[5]/q u_uart_core/rx_timeout_cnt_regx5x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[4]/q u_uart_core/rx_timeout_cnt_regx4x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[3]/q u_uart_core/rx_timeout_cnt_regx3x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[2]/q u_uart_core/rx_timeout_cnt_regx2x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[1]/q u_uart_core/rx_timeout_cnt_regx1x/Q -type DFF DFF
add mapped point u_uart_core/lsr_pe/q u_uart_core/lsr_pe_reg/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_flag/q u_uart_core/rx_timeout_flag_reg/Q -type DFF DFF
add mapped point u_uart_core/lsr_oe/q u_uart_core/lsr_oe_reg/Q -type DFF DFF
add mapped point u_uart_core/FCR_q[6]/q u_uart_core/FCR_q_regx6x/Q -type DFF DFF
add mapped point u_uart_core/FCR_q[7]/q u_uart_core/FCR_q_regx7x/Q -type DFF DFF
add mapped point u_uart_core/rx_timeout_cnt[0]/q u_uart_core/rx_timeout_cnt_regx0x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[0]/q u_uart_core/IER_q_regx0x/Q -type DFF DFF
add mapped point u_uart_core/MCR_q[4]/q u_uart_core/MCR_q_regx4x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[2]/q u_uart_core/DLL_q_regx2x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[1]/q u_uart_core/LCR_q_regx1x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[2]/q u_uart_core/LCR_q_regx2x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[3]/q u_uart_core/LCR_q_regx3x/Q -type DFF DFF
add mapped point u_uart_core/MCR_q[0]/q u_uart_core/MCR_q_regx0x/Q -type DFF DFF
add mapped point u_uart_core/MCR_q[1]/q u_uart_core/MCR_q_regx1x/Q -type DFF DFF
add mapped point u_uart_core/MCR_q[2]/q u_uart_core/MCR_q_regx2x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[0]/q u_uart_core/LCR_q_regx0x/Q -type DFF DFF
add mapped point u_uart_core/MCR_q[3]/q u_uart_core/MCR_q_regx3x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[3]/q u_uart_core/DLL_q_regx3x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[4]/q u_uart_core/DLL_q_regx4x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[1]/q u_uart_core/DLL_q_regx1x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[3]/q u_uart_core/IER_q_regx3x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[6]/q u_uart_core/DLL_q_regx6x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[7]/q u_uart_core/DLL_q_regx7x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[4]/q u_uart_core/DLM_q_regx4x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[0]/q u_uart_core/DLM_q_regx0x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[1]/q u_uart_core/DLM_q_regx1x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[2]/q u_uart_core/DLM_q_regx2x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[3]/q u_uart_core/DLM_q_regx3x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[5]/q u_uart_core/DLM_q_regx5x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[6]/q u_uart_core/DLM_q_regx6x/Q -type DFF DFF
add mapped point u_uart_core/DLM_q[7]/q u_uart_core/DLM_q_regx7x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[1]/q u_uart_core/IER_q_regx1x/Q -type DFF DFF
add mapped point u_uart_core/IER_q[2]/q u_uart_core/IER_q_regx2x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[5]/q u_uart_core/DLL_q_regx5x/Q -type DFF DFF
add mapped point u_uart_core/DLL_q[0]/q u_uart_core/DLL_q_regx0x/Q -type DFF DFF
add mapped point u_uart_core/LCR_q[6]/q u_uart_core/LCR_q_regx6x/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
